apiVersion: apps/v1
kind: Deployment
metadata:
  name: automl-frontend
  namespace: zauto
spec:
  replicas: 1
  selector:
    matchLabels:
      team: bdilab
  template:
    metadata:
      labels:
        team: bdilab
    spec:
      nodeName: master # 可选
      containers:
        - name: automl-frontend
          image: registry.cn-hangzhou.aliyuncs.com/treasures/automl-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # Pod端口，应和应用程序监听端口一致

---
apiVersion: v1
kind: Service
metadata:
  name: automl-frontend
  namespace: zauto
spec:
  type: NodePort
  ports:
    - port: 32000 # Service端口，映射Pod中的容器端口，可被外部访问
      targetPort: 8080 # Pod容器端口
      nodePort: 32000
  selector:
    team: bdilab
