# local pv-pvc
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: automl-metadata-pv
# spec:
#   capacity:
#     storage: 50Gi
#   accessModes:
#     - ReadOnlyMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: nfs-automl
#   local:
#     path: /nfs/automl/huggingface/model
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/hostname
#               operator: In
#               values:
#                 - node1
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: automl-metadata-pvc
#   namespace: zauto # 必须和pod在同一名称空间下
# spec:
#   accessModes:
#     - ReadOnlyMany
#   storageClassName: nfs-automl
#   resources:
#     requests:
#       storage: 50Gi

# nfs pv-pvc
apiVersion: v1
kind: PersistentVolume
metadata:
  name: automl-metadata-pv
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteMany
#    - ReadOnlyMany
  volumeMode: Filesystem
  nfs:
    path: /nfs/automl/workspace/python/automl/alserver/metadata
    server: 192.168.0.188
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-automl

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automl-metadata-pvc
  namespace: zauto # 必须和pod在同一名称空间下
spec:
  accessModes:
    - ReadWriteMany
#    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: nfs-automl
