apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: automl-backend-java
  namespace: zauto
spec:
  serviceName: automl-backend-java
  replicas: 1
  selector:
    matchLabels:
      team: bdilab
  template:
    metadata:
      labels:
        team: bdilab
    spec:
      nodeName: master
      containers:
        - name: automl-deployment
          image: automl-java:v0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 32081 # Pod端口，应和应用程序监听端口一致
          resources:
            requests:
              cpu: "0.5" # 请求的CPU资源
            limits:
              cpu: "1" # CPU资源的限制
          securityContext:
            privileged: true  # 请求特权模式
            runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: automl-backend-java
  namespace: zauto
spec:
  type: NodePort
  ports:
    - port: 32081 # Service端口，映射Pod中的容器端口，可被外部访问
      targetPort: 32081 # Pod容器端口
      nodePort: 32081
  selector:
    team: bdilab
