# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: automl-metadata-pv
# spec:
#   capacity:
#     storage: 60Gi
#   accessModes:
#     - ReadWriteMany
#   volumeMode: Filesystem
#   nfs:
#     path: /nfs/automl/workspace/python/automl/alserver/metadata
#     server: 192.168.0.188
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: nfs-automl

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: automl-metadata-pvc
#   namespace: zauto # 必须和pod在同一名称空间下
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 10Gi
#   volumeMode: Filesystem
#   storageClassName: nfs-automl

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: automl-kube-config-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /root/.kube/config
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kube-config-automl

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automl-kube-config-pvc
  namespace: zauto # 必须和pod在同一名称空间下
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: kube-config-automl
